/** Action Types for userBook state */
export const ADD_NEW_USER_BOOK_LOADING = 'ADD_NEW_USER_BOOK_LOADING';
export const ADD_NEW_USER_BOOK_SUCCESS = 'ADD_NEW_USER_BOOK_SUCCESS';
export const ADD_NEW_USER_BOOK_ERROR = 'ADD_NEW_USER_BOOK_ERROR';

export const USER_BOOKS_LOADING = 'USER_BOOKS_LOADING';
export const USER_BOOKS_SUCCESS = 'USER_BOOKS_SUCCESS';
export const USER_BOOKS_ERROR = 'USER_BOOKS_ERROR';

/** Action Types for book state */
export const BOOK_TITLE_SUGGESTION_LOADING = 'BOOK_TITLE_SUGGESTION_LOADING';
export const BOOK_TITLE_SUGGESTION_SUCCESS = 'BOOK_TITLE_SUGGESTION_SUCCESS';
export const BOOK_TITLE_SUGGESTION_ERROR = 'BOOK_TITLE_SUGGESTION_ERROR';
